### ISSUE TITLE
refs have wrong properties on callback

### ISSUE THREAD

**Issue by queckezz** [ashaffer/virtex-local#3]
Given

``` js
const render = () => {
  return (
    <button class={buttonStyle}>
      Click to Ripple

      <canvas
        class={canvasStyle}
        style={{ width: percent(100), height: percent(100) }}
        ref={canvas => {
          console.dir(canvas)
          console.log(canvas.offsetWidth)
        }}
      >
      </canvas>
    </button>
  )
}
```

Output of `console.dir` returns the correct offsetHeight, offsetWidth:
![image](https://cloud.githubusercontent.com/assets/2580598/12054868/796b3ffa-af27-11e5-8116-f1eef2095308.png)

When logging `canvas.offsetWidth` it returns me **`0`** though.

Not sure what's going on here. Do you have any ideas?

Also, I need to do some canvas manipulations, how can I keep a reference to the `canvas` element? My approach would be to dispatch an action in the `ref` handler saving `canvas.getContext('2d')`, `offsetWidth` and `offsetHeight`.

Thanks for all the great work with virtex again! I was about to do a pull request adding a `context` like in react/deku for vdux but I saw you put some `refactor` branches up, so I'm going to wait ;)

**Comment by queckezz** [comment]
Just noticed that I'm able to get the correct value with:

``` js
setTimeout(() => console.log(canvas.offsetWidth), 0)
// -> 150
```

But  I need to synchronously `return` an action, how am I able `dispatch` `offsetWidth` etc.?

**Comment by ashaffer** [comment]
Hmm...I think you might have the wrong idea about `ref`. Ref is a special attribute that you should only use with `ref.to` and `ref.as`. It doesn't give you a reference to the raw element, it gives you the ability to send actions to that component.

If you want access to the raw element, you can do put a function on any other attribute, like this:

``` javascript
const render = () => {
  return (
    <button class={buttonStyle}>
      Click to Ripple

      <canvas
        class={canvasStyle}
        style={{ width: percent(100), height: percent(100) }}
        hook={canvas => {
          console.dir(canvas)
          console.log(canvas.offsetWidth)
        }}
      >
      </canvas>
    </button>
  )
}
```

`hook` being any attribute you want that doesn't already have a special purpose (like ref).

**Comment by queckezz** [comment]
Ah I see, thank you. I assumed it's similar too react since you explained it that way in vdux docs:

> ref - Used for inter-component communication, **and analogous to React's refs**.

From what I understand, react's `refs` is exactly for accessing raw dom elements (at least in <0.14):

``` js
<input type="text" ref={(ref) => this.myTextInput = ref} />
```

**Comment by ashaffer** [comment]
Ya I should probably clarify that better. I meant that you can use it to call functions on other components (sort of), but I should probably make that more clear.
