### ISSUE TITLE
local actions (via events) don't go through middleware

### ISSUE THREAD

**Issue by queckezz** [ashaffer/virtex-local#4]
https://github.com/ashaffer/virtex-local/blob/master/src/index.js#L75

``` js
thunk.type.reducer(thunk.state, fn.apply(thunk, outerArgs.concat(innerArgs))
```

This is just basic reducer but no dispatching of the local action through the middleware system. So stuff  like `redux-multi` or `redux-logger` won't work. I find `redux-logger` almost essential to the whole architecture:

``` js
return (
  <button onClick={local(e => {
    return [
      action1(),
      action2()
    ]
  })}>
    Button
  </button>
)
```

I think `dispatch(fn.apply(thunk, outerArgs.concat(innerArgs)))` should work? 

**Edit:** This would mean we would enforce that all local actions need to be scoped globally, so

``` js
const localAction = createAction('@myComponent/action')
```

Or we could also additionally add  `{ __local: true }` to `action.meta` so we can have some kind of information when debugging that this is indeed a local action and remove those from the global reducing function.

``` js
// virtex-local
const action = fn.apply(thunk, [...outerArgs, ...innerArgs])
action.meta = { ...action.meta, __local: true }

// vdux-preset-client
import { ignoreActions } from 'redux-ignore';
ignoreActions(reducer, (action) => action.meta.__local)

```

**Sidenote:**
For me as a contributor it's almost impossible to test because I have to fork vdux and connect it to my forked `virtex-local` branch to finally test it. If something goes wrong I need to update `virtex-local` again, push it and then test again. They are spread across even though they depend on each other so closely. Making changes this way is hard. Most of the time you work on `virtex`, `virtex-local` etc. together, right? Definitely would prefer tests locally to the repository. And if that's not possible maybe it's better to merge it into one library like deku, [recompose](https://github.com/acdlite/recompose/tree/master/src) or babeljs does?

**Comment by queckezz** [comment]
Also, what do you think of some kind of a `displayName` like react has? We could then have a wrapper around redux-logger which displays grouped local actions per component:

(group) **action** AUTHENTICATE @ time in 0.02ms
(group) **local-action** from **Dropdown** OPEN @ time in 0.02ms

**Comment by ashaffer** [comment]
Ahh, I had been wondering if I was going to have to go back to dispatching through the middleware. I did it that way originally, then simplified it to this, but you're totally right, needs to go through middleware. I'll put that back.

As for how to scope them, I originally had it such that it would wrap local actions in a `LOCAL_ACTION` type action with the actual local action as a payload, but I realize now that that wouldn't work for redux-multi, and it was annoying to use with redux-logger. The reason I did that was so that you didn't have to think about the global action namespace when you were writing local actions, which seems like a nice property - but perhaps it's all just inherently global. The ignore actions thing seems maybe too complicated? I'm not sure, I think just making it the user's responsibility to scope their actions seems appropriate.

Ultimately though, you kind of have this issue with redux-multi, where the `local` function is wrapping a thing, and it is always going to be wrapping it before multi gets to it. So the `local` function either has to just stick a `.meta` right on the array, and multi has to start knowing to merge that meta into its child actions' meta, or `local` has to know about arrays, and add `.meta` onto each element. The former seems somewhat more general, but also a little weird to throw a `.meta` on an array.

As for tests, I use npm link. It's slightly annoying, but you shouldn't have to git push each time. Just npm link virtex-local, then run `babel src --out-dir lib` in virtex-local, and it'll rebuild the lib folder and hihat in your virtex folder will automatically reload.

**Comment by queckezz** [comment]
> didn't have to think about the global action namespace when you were writing local actions, which seems like a nice property 

Yes exactly. I like that too. It would be cool if we can somehow differentiate local and global actions even if we need to wrap `redux-logger` for nicer output.

▾**action** AUTHENTICATE @ time in 0.02ms
▾**local-action** from **Dropdown** OPEN @ time in 0.02ms

> As for tests, I use npm link. It's slightly annoying, but you shouldn't have to git push each time. Just npm link virtex-local, then run babel src --out-dir lib in virtex-local, and it'll rebuild the lib folder and hihat in your virtex folder will automatically reload.

Ah nice. Can you maybe add your test routine with `hihat` to `package.json` `scripts`?

**Comment by ashaffer** [comment]
> Yes exactly. I like that too. It would be cool if we can somehow differentiate local and global actions even if we need to wrap redux-logger for nicer output.

Ya that would be very nice. Right now i'm leaning towards just blindly sticking `.meta` on there, and then having redux-multi propagate `.meta` into its children. Or maybe just saying that you shouldn't wrap array-returning functions with `local`. Like you should wrap the individual functions in the arrays with local, and then you can have a mixture of local and non-local actions. Not sure yet. But it'd be very nice to have pretty redux-logger output like that.

> Ah nice. Can you maybe add your test routine with hihat to package.json scripts?

Oh, ya you're right I should do that. At the moment it's in the Makefile though. `make test` will run them. But ya, I should add it to package.json as well, and maybe document the npm link thing so other people don't have that issue.

**Comment by ashaffer** [comment]
@queckezz Hey man, just published a new version of vdux, virtex, redux-ephemeral et al that addresses this amongst other things. Now actions go through middleware, and they are scoped just to the reducer they're directed at. Let me know what you think of the new stuff.

**Comment by queckezz** [comment]
Straight up awesome! Hyped to try it out. 

How about moving

> vdux is an opionated, higher-level abstraction over redux and virtex

to the top level of the vdux readme and remove

> Stateless virtual dom <-> Redux

I find this much more descriptive.

**Comment by queckezz** [comment]
40mins to do a `npm install`, just to run some examples :(

**Comment by ashaffer** [comment]
40 minutes!? On what version of npm!?

**Comment by queckezz** [comment]
`3.5.2` seems like it's not the size of those packages but the individual small packages which each take up a lot of time.

![image](https://cloud.githubusercontent.com/assets/2580598/12221269/9b1f98ac-b793-11e5-95a9-e2dcc3277e0f.png)

**Comment by ashaffer** [comment]
Ya, I think it's all the babel stuff. I mean, I think micro-js packages are probably contributing, but I think it's mostly babel 6's doing, and all its modules. I'd really like to just not include babel at all in my dev deps, but I think that's frowned upon. You have any ideas on what to do there?

EDIT: I installed it locally and it took about a minute and a half. Not good at all, but nowhere near 40 minutes. Maybe npm had some weird intermittent issue during your install?

**Comment by queckezz** [comment]
Could be or my internet is just slow. I don't have any alternatives atm. Anyway I've found some wierd issues on the `routing` example. 

In `components/layouts/main.js` children is actually undefined but it seems everything is hooked up correctly.

``` js
const {nav, children} = props // children -> undefined
```

The entire `<MainLayout>` also gets removed and inserted on every click. Is this intended? I don't really have too much experience about that stuff.

![animation](https://cloud.githubusercontent.com/assets/2580598/12221342/60145e88-b797-11e5-9b4e-06859eb24e4f.gif)

**Comment by ashaffer** [comment]
Oh, I should add a note about that. The routing example is incomplete, just ignore that for now, i'm still working on that.

As for the install issue, I tried installing deku as well and had a similarly slow install time. I'm pretty sure it's just babel 6 being insane with its dependencies. I think the options are either downgrade to babel 5 or try to remove babel from the dev deps and just depend on its global presence. Any thoughts?

**Comment by ashaffer** [comment]
> How about moving
> 
> > vdux is an opionated, higher-level abstraction over redux and virtex
> 
> to the top level of the vdux readme and remove
> 
> > Stateless virtual dom <-> Redux
> 
> I find this much more descriptive.

Let me think about that - I think my reasoning here is that 'stateless virtual dom <-> redux' captures the conceptual overview of what vdux is all about, whereas 'opinionated higher level abstraction over redux and virtex' isn't all that meaningful unless you already know what virtex is and are familiar with the philosophy of the project.

I'm not sure either actually make a great one-line intro/description. I'd like to have one that explains succintly what it does and why, without invoking references to its submodules (until a bit later).

**Comment by queckezz** [comment]
The Installation times are pretty slow but something just went horribly wrong on my end. I think 1 1/2 minutes like you had is still acceptable. Depending on global presence might introduce some problems when somebody is using `babel@5` and your project is depending on `babel@6`. 

> Let me think about that - I think my reasoning here is that 'stateless virtual dom <-> redux' captures the conceptual overview of what vdux is all about, whereas 'opinionated higher level abstraction over redux and virtex' isn't all that meaningful unless you already know what virtex is and are familiar with the philosophy of the project.

You're right, not ideal. I'm not particularly good at this but I'll give it a try:

`vdux` is a tiny view library encouraging **pure,  stateless and composable user interfaces** using virtual dom.
